# Generated by Django 5.2.7 on 2025-10-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionarios',
            old_name='cpd',
            new_name='cpf',
        ),
    ]
