# Generated by Django 5.2.7 on 2025-11-05 00:40

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_rename_cpd_funcionarios_cpf'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='funcionarios',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
